### ISSUE TITLE
come si usano i metadati?

### ISSUE THREAD

**Issue by faina09** [italia/spid-dotnet-sdk#11]
il link in 
`La chiave così esportata è un mero file di testo che contiene la chiave pubblica da copiare nell'apposito campo della pagina web di creazione del file di metadati.` non funziona.

Inoltre non è per nulla chiaro come `Il file XML contenente i metadati creato dalla suddetta pagina va poi utilizzato per registrare la nostra applicazione Web`

tentativi di accesso alla pagina del SP danno l'errore:
`Formato richiesta non corretto`

**Comment by ncarandini** [comment]
La pagina linkata non è più attiva, grazie della segnalazione, che riporterò a chi di dovere (la pagina non è gestita da questo progetto. Si trattava di una pagina che aiutava a compilare il file metadata (compliant alle[ Regole Tecniche SPID](http://spid-regole-tecniche.readthedocs.io/en/latest/regole-tecniche-idp.html#metadata)) di cui puoi trovare un esempio qui: http://spid-regole-tecniche.readthedocs.io/en/latest/regole-tecniche-idp.html#esempio-metadata-idp

Hai ragione sul fatto che non è chiaro, migliorerò la documentazione, con notizie più specifiche. Il concetto comunque è quello di fornire tale documento ai vari Identity Providers ([elenco ufficiale AgID](http://www.agid.gov.it/infrastrutture-architetture/spid/identity-provider-accreditati)). Se non ti accrediti, nessuna tua richiesta verrà riconosciuta.

**Comment by alexrj** [comment]
Tutte le indicazioni su come diventare Service Provider sono in questa pagina:
https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid

Per testare la propria implementazione, invece, si può usare l'ambiente di test SPID disponibile all'indirizzo https://idp.spid.gov.it:8080/ oppure https://github.com/italia/spid-testenv

**Comment by ncarandini** [comment]
Chiedo venia per la mia ignoranza in materia di messa in produzione di un servizio che utilizza SPID, mi sono informato e mi è stato spiegato che il file di metadati non va inviato (per fortuna) ad ogni singolo IdP (Identity Provider) ma solo all'AgID (Agenzia per l'Italia Digitale).
La procedura al momento passa per la creazione di un ticket (ovvero l'apertura di una issue) nel sito https://github.com/italia/spid.
Mercoledì prossimo ho la possibilità di parlarne estesamente in AgID, quindi sarò poi in grado di documentare l'iter in modo più esaustivo.

**Comment by faina09** [comment]
grazie a tutti, su un PC Windows10 ho usato il codice qui disponibile per realizzare il mio prototipo e l'implementazione di @alexrj per Docker di un "[Identity Provider da far girare in locale o su un proprio server](https://github.com/italia/spid-testenv-docker)" utile per testare la propria integrazione con SPID senza avere a disposizione identità SPID reali.

**Comment by ncarandini** [comment]
Ottimo, se hai altre necessità non esitare ad aprire una nuova issue ;-)
