### ISSUE TITLE
chiave non utilizzabile nello stato specificato

### ISSUE THREAD

**Issue by msirio** [italia/spid-dotnet-sdk#14]
Ciao a tutti,
Dopo aver effettuato la creazione del certificato e la sua importazione tramite MMC, durante l'esecuzione (in debug) mi appare il seguente errore:  chiave non utilizzabile nello stato specificato.
Qualcuno sa dirmi a cosa è dovuto ?

Grazie

**Comment by stepetra** [comment]
Ciao,
aperto da MMC lo store dove si trova il certificato, prova a fare sul
certificato (vado a memoria) tasto DX -> all task -> Manage keys.
Nei diritti aggiungi l'utente che deve accedere alle informazioni (al
limite everyone o users sola lettura).
Saluti.

Stefano



Il giorno lun 30 lug 2018 alle ore 13:47 msirio <notifications@github.com>
ha scritto:

**Comment by almaxstudio** [comment]
Salve, 

dopo svariati tentativi sono arrivato allo stesso probema "Chiave non utilizzabile nello stato specificato" come avete risolto. Ho abilitato i permessi in lettura per users everyone e iis_usr ma nulla.

Grazie

**Comment by almaxstudio** [comment]
> 
> 
> Salve,
> 
> dopo svariati tentativi sono arrivato allo stesso problema "Chiave non utilizzabile nello stato specificato" come avete risolto. Ho abilitato i permessi in lettura per users everyone e iis_usr ma nulla.
> 
> Grazie

Per spirito di collaborazione riporto come ho risolto il problema: quando si importa il certifica nella console di gestione dei certificati bisogna selezionare il checkbox "Contrassegna la chiave come esportabile ... " 

Un saluto
