### ISSUE TITLE
Implementazione chiamate SAML con redirect 

### ISSUE THREAD

**Issue by congiuluc** [italia/spid-dotnet-sdk#8]
Al momento la libreria prevede solo chiamate POST in realtà il protocollo SAML prevede la possibilità di fare il binding anche con redirect

**Comment by ncarandini** [comment]
Ciao @congiuluc,
nel prossimo futuro è previsto un coordinamento organizzato da @alexrj per definire un set di funzionalità comuni a tutte le librerie nei diversi linguaggi / framework.
Se del caso la implementeremo, altrimenti no, perché spid-dotnet-sdk non è una implementazione generica e completa del protocollo SAML2 quanto piuttosto di SPID.
